# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

bindkey "jk" vi-cmd-mode
bindkey -M vicmd '/' history-incremental-search-backward

# bolt fonts in terminal
export LSCOLORS=ExFxBxDxCxegedabagacad

export HOMEBREW_EDITOR=vim
export TERM=xterm-256color

case "$OSTYPE" in
  linux*)   export BREW=$HOME/.linuxbrew ;;
  darwin*)  export BREW=$HOME/.homebrew ;;
esac

export PATH=''
export CPATH=''
export LIBRARY_PATH=''

SOURCES=($HOME/.miniforge $BREW $HOME/.local /usr/local /usr /)

for i in ${SOURCES[*]}; do

    export PATH=$PATH:$i/bin
    export PATH=$PATH:$i/sbin
    export CPATH=$CPATH:$i/include
    export LIBRARY_PATH=$LIBRARY_PATH:$i/lib

done


export LD_LIBRARY_PATH=$HOME/.cuda/lib64:$LD_LIBRARY_PATH
export PATH="$HOME/.cuda/bin:$PATH"
alias tm='tmux attach || tmux new'

# >>> conda initialize >>>
__conda_setup="$('$HOME/.miniforge/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/.miniforge/etc/profile.d/conda.sh" ]; then
        . "$HOME/.miniforge/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/.miniforge/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "$HOME/.miniforge/etc/profile.d/mamba.sh" ]; then
    . "$HOME/.miniforge/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<