# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi
bindkey "jk" vi-cmd-mode
bindkey -M vicmd '/' history-incremental-search-backward

# bolt fonts in terminal
export LSCOLORS=ExFxBxDxCxegedabagacad

#alias ipython='ipython --pylab'
alias display="display -update 2"
alias tunnel_vlc='ssh -NfL 44444:localhost:5900 limoges'

#bug with git, can be removed soon
export SSH_AUTH_SOCK=0
export HOMEBREW_EDITOR=vim
export TERM=xterm-256color


export PATH=''
export CPATH=''
export LIBRARY_PATH=''
#
case "$OSTYPE" in
  linux*)   export BREW=$HOME/.linuxbrew ;;
  darwin*)  export BREW=$HOME/.homebrew ;;
  win*)     echo "Windows" ;;
  cygwin*)  echo "Cygwin" ;;
  bsd*)     echo "BSD" ;;
  solaris*) echo "SOLARIS" ;;
  *)        echo "unknown: $OSTYPE" ;;
esac

export PATH=$PATH:${CONDOR_HOME}/bin

SOURCES=( $HOME/.miniconda $BREW /usr/local /usr /)
#SOURCES=( $HOME/.local/cuda $HOME/.miniconda $BREW /usr/local /usr /)
for i in ${SOURCES[*]}; do

    export PATH=$PATH:$i/bin
    export PATH=$PATH:$i/sbin
    export CPATH=$CPATH:$i/include
    export LIBRARY_PATH=$LIBRARY_PATH:$i/lib
    #export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$i/lib

done
#export PATH=$PATH:/usr/texbin
export PATH=$PATH:/usr/local/texlive/2018/bin/x86_64-darwin


#Python environment and settings
export PYTHONWARNINGS="ignore"

export LD_LIBRARY_PATH=$HOME/.cuda/lib64:$LD_LIBRARY_PATH
#export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$HOME/.cuda/lib$DYLD_LIBRARY_PATH
export PATH="$HOME/.cuda/bin:$PATH"

# use autoenv to manage virtual environments
source $BREW/opt/autoenv/activate.sh
smart_env3 () {
    dir=${PWD##*/}
    echo $dir
    yes | conda create python=3.6 -p $PWD/.$dir
    echo "source activate $PWD/.$dir" > .env
    echo ".env*\n.$dir" > .gitignore
    yes | cd $PWD >/dev/null 2>&1
    yes | conda install numpy
    pip install ipdb
}
smart_env2 () {
    dir=${PWD##*/}
    echo $dir
    yes | conda create python=2.7 -p $PWD/.$dir
    echo "source activate $PWD/.$dir" > .env
    echo ".env*\n.$dir" > .gitignore
    yes | cd $PWD >/dev/null 2>&1
    yes | conda install numpy
    pip install ipdb
}
export PYTHONPATH=$PYTHONPATH:/Users/robert.walecki/projects/pgm-cv
export PYTHONPATH=$PYTHONPATH:/Users/robert.walecki/projects/data-science-research/disability-w-pred/utils
alias tm="tmux attach || tmux new"
